isi_angka = input("Masukkan beberapa angka dengan spasi: ")
angka = list(map(float, isi_angka.split(' ')))
rata_angka = sum(angka)/len(angka)
print("List yang didapatkan dari inputan: ")
print(angka)
print()
print("Maka kita dapat menghitung totalnya adalah %s"%(sum(angka)))
print("Dengan nilai rata-rata %s"%(rata_angka))
print("Nilai terbesarnya adalah %s dan terkecilnya adalah %s"%(max(angka), min(angka)))