isi_belanja = input("Masukkan 5 barang yang mau kamu beli (pisahkan dengan ','): ").lower()
belanja = list(isi_belanja.split(','))
print("Ini adalah daftar belanja anda: ")
print(belanja)
hapus_belanja = input("Hapus satu barang yang sudah kamu beli: ").lower()
belanja.remove(hapus_belanja)
print()
print("Sekarang sisa belanjaan kamu adalah: ")
print(belanja)